/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FlexBox: typeof import('./src/components/FlexBox.vue')['default']
    MaterialButton: typeof import('./src/components/MaterialButton.vue')['default']
    OptionalRouterLink: typeof import('./src/components/OptionalRouterLink.vue')['default']
    PBadge: typeof import('primevue/badge')['default']
    PDrawer: typeof import('primevue/drawer')['default']
    PToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerticalToolbar: typeof import('./src/components/VerticalToolbar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('primevue/ripple')['default']
    vTooltip: typeof import('primevue/tooltip')['default']
  }
}
