baseURL = "https://tclement0922.github.io/"
title = "T. Clément"
theme = "hello-friend-ng"
copyright = "Licensed under <a href=\"https://github.com/tclement0922/tclement0922.github.io/blob/master/LICENSE\" target=\"_blank\" rel=\"noopener\">The MIT License (MIT)</a>"
paginate = 10

[minify]
  minifyOutput = true

[params]
  enableThemeToggle = true
  enableGlobalLanguageMenu = false
  enableSharingButtons = false

  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "17 yo french student who likes coding"
  description = "Personal website of tclement0922, a french student."
  keywords = "tclement0922, homepage"
  images = [""]

  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = false

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Theme by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  [params.logo]
    logoMark = ">"
    logoText = "tclement0922"
    logoHomeLink = "/"

  [params.portrait]
    path = "https://github.com/tclement0922.png"
    alt = "Avatar"
    maxWidth = "100px"

  [[params.social]]
    name = "github"
    url = "https://github.com/tclement0922"

  [[params.social]]
    name = "email"
    url = "mailto:hi+dev.tclement0922@gmail.com"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
